services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secure-password
      - POSTGRES_DB=school-trip-api
    volumes:
      - school-trip-api:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  smtp:
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: true
      MP_SMTP_AUTH_ALLOW_INSECURE: true

volumes:
  school-trip-api: