services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secure-password
      - POSTGRES_DB=school-trip-api
    volumes:
      - school-trip-api-sql-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secure-password
      - MONGO_INITDB_DATABASE=school-trip-api
    volumes:
      - school-trip-api-nosql-db:/data/db
    ports:
      - "27017:27017"
    
  
  smtp:
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: true
      MP_SMTP_AUTH_ALLOW_INSECURE: true

volumes:
  school-trip-api-sql-db:
  school-trip-api-nosql-db: