services:
  database:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secure-password
      - POSTGRES_DB=dot-net-five-api-demo
    volumes:
      - dotnet-five-api-demo:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  smtp:
    image: axllent/mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: true
      MP_SMTP_AUTH_ALLOW_INSECURE: true

volumes:
  dotnet-five-api-demo: